# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('upassword', models.TextField(max_length=20)),
                ('dob', models.DateField()),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('Hyd', 'Hyderabad'), ('Chi', 'Chennai'), ('Bgn', 'Banglore'), ('Msr', 'Mysore')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
            ],
        ),
    ]
