# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_auto_20181219_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
