# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-19 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0003_auto_20181219_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='dob',
            field=models.DateField(),
        ),
    ]
