# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0004_auto_20181220_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
