# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-20 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0005_auto_20181220_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
