# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0006_auto_20181220_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
