# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-20 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0007_auto_20181220_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdata',
            name='dob',
        ),
    ]
